<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please compress the size of the image,click on the display of the compressed address.' => '请压缩图像的大小，点击显示压缩地址。', 
    '{attribute} error.' => '{attribute}错误。',
    'Incorrect username or password.' => '账号或密码错误。',
    'You do not have permission to sign in.' => '你没有登录权限。',
    'The user has been removed.' => '该用户已经被删除。',
    'The user has been disabled.' => '该用户已经被禁用。',
    '{attribute} format error, must be 11 mobile phone number' => '{attribute}格式错误，必须为11位手机号。',
    'System to identify your birthday is illegal, please ensure that the age of the birthday between 1-120 years of age'  => '系统识别你的生日非法，请确保1-120岁年龄之间的生日。',
];
