<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => '增加',
    'Delete' => '删除',
    'Deleted' => '已删除',
    'Update' => '修改',
    'Query' => '查询',
    'Info' => '消息',
    'Error' => '错误',
    'Success' => '成功',
    'Fail' => '失败',
    'Warning' => '警告',
    'Unknown' => '未知',
    'Male' => '男',
    'Female' => '女',
    'Normal' => '正常',
    'Disable' => '禁用',
    'Disabled' => '已禁用',
    'Apple' => '苹果',
    'Ipad' => 'Ipad',
    'Android' => '安卓',
    'Android Tablet' => '安卓平板',
    'Computer' => '电脑',
    'Web' => '网站',
    'Mobile Web' => '手机网站',
    'Wechat' => '微信',
    'Backend' => '后台',
    'Admin' => '系统管理员',
    'Manager' => '管理员',
    'Backend User' => '后台用户',
    'User' => '用户',
    'Checked' => '已核对',
    'Bank Transfer' => '银行转账',
    'Wechat' => '微信',
    'Alipay' => '支付宝',
    'Unpaid' => '未付款',
    'Paid' => '已付款',
    'Shipped' => '已发货',
    'Completed' => '已完成',
    'Canceled' => '已取消',

    'No Invoice' => '无发票',
    'Plain Invoice' => '普通发票',
    'VAT Invoice' => '增值发票',
    'Individual' => '个人',
    'Enterprise' => '企业',


    'Hour' => '小时',
    'Day' => '天',
    'Month' => '月',

    'Fixed' => '固定',
    'Unlimited' => '无限制',

    'Audit' => '审核中',
    'Audit Return' => '审核退回',
    'Audit Through' => '审核通过',


];
